export type BookingReceipt = {
  id: string;
  businessName: string;
  serviceName: string;
  staffName: string | null;
  locationName: string | null;
  startsAt: string;
  endsAt: string;
  customerName: string;
  customerPhone: string;
  customerEmail: string | null;
  price: number;
  currency: string;
  paymentStatus: string;
  businessPhone: string | null;
  businessEmail: string | null;
};

function safeFilePart(value: string) {
  return value.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");
}

export async function downloadBookingReceipt(receipt: BookingReceipt) {
  const { PDFDocument, StandardFonts, rgb } = await import("pdf-lib");
  const pdf = await PDFDocument.create();
  const page = pdf.addPage([595, 842]);
  const regular = await pdf.embedFont(StandardFonts.Helvetica);
  const bold = await pdf.embedFont(StandardFonts.HelveticaBold);
  const navy = rgb(0.045, 0.102, 0.22);
  const blue = rgb(0.055, 0.42, 0.88);
  const muted = rgb(0.38, 0.43, 0.52);
  const pale = rgb(0.94, 0.97, 1);
  const left = 54;

  page.drawRectangle({ x: 0, y: 746, width: 595, height: 96, color: navy });
  page.drawRectangle({ x: left, y: 782, width: 30, height: 4, color: blue });
  page.drawText(receipt.businessName, { x: left, y: 801, size: 20, font: bold, color: rgb(1, 1, 1) });
  page.drawText("BOOKING RECEIPT", { x: left, y: 767, size: 10, font: bold, color: rgb(0.72, 0.84, 1) });
  page.drawText(`#${receipt.id.slice(0, 8).toUpperCase()}`, { x: 430, y: 767, size: 10, font: bold, color: rgb(1, 1, 1) });

  page.drawText("Appointment confirmed", { x: left, y: 700, size: 22, font: bold, color: navy });
  page.drawText("Keep this receipt for your records.", { x: left, y: 679, size: 10, font: regular, color: muted });

  page.drawRectangle({ x: left, y: 557, width: 487, height: 94, color: pale });
  page.drawText(receipt.serviceName, { x: 72, y: 620, size: 15, font: bold, color: navy });
  const appointmentDate = new Date(receipt.startsAt);
  const dateLabel = appointmentDate.toLocaleDateString("en-GB", {
    weekday: "long",
    day: "numeric",
    month: "long",
    year: "numeric",
  });
  const timeLabel = appointmentDate.toLocaleTimeString("en-GB", { hour: "2-digit", minute: "2-digit" });
  page.drawText(`${dateLabel} at ${timeLabel}`, { x: 72, y: 596, size: 11, font: regular, color: navy });
  if (receipt.staffName) page.drawText(`With ${receipt.staffName}`, { x: 72, y: 575, size: 10, font: regular, color: muted });
  if (receipt.locationName) page.drawText(receipt.locationName, { x: 320, y: 575, size: 10, font: regular, color: muted });

  const rows: [string, string][] = [
    ["Customer", receipt.customerName],
    ["Phone", receipt.customerPhone],
    ["Email", receipt.customerEmail || "Not provided"],
    ["Payment", receipt.paymentStatus === "paid" ? "Paid" : "Payment due at appointment"],
  ];
  let y = 510;
  for (const [label, value] of rows) {
    page.drawText(label, { x: left, y, size: 9, font: bold, color: muted });
    page.drawText(value, { x: 180, y, size: 10, font: regular, color: navy });
    y -= 30;
  }

  page.drawLine({ start: { x: left, y: 368 }, end: { x: 541, y: 368 }, thickness: 1, color: rgb(0.86, 0.89, 0.93) });
  page.drawText("Total", { x: left, y: 335, size: 13, font: bold, color: navy });
  const total = new Intl.NumberFormat("en", { style: "currency", currency: receipt.currency }).format(receipt.price);
  page.drawText(total, { x: 430, y: 335, size: 15, font: bold, color: blue });

  const contact = [receipt.businessPhone, receipt.businessEmail].filter(Boolean).join("  •  ");
  page.drawText("Questions or changes? Contact the business directly.", { x: left, y: 110, size: 9, font: regular, color: muted });
  if (contact) page.drawText(contact, { x: left, y: 92, size: 9, font: bold, color: navy });
  page.drawText("Generated by BookFlow", { x: left, y: 48, size: 8, font: regular, color: muted });

  const bytes = await pdf.save();
  const blob = new Blob([bytes as BlobPart], { type: "application/pdf" });
  const url = URL.createObjectURL(blob);
  const anchor = document.createElement("a");
  anchor.href = url;
  anchor.download = `${safeFilePart(receipt.businessName)}-booking-${receipt.id.slice(0, 8)}.pdf`;
  anchor.click();
  URL.revokeObjectURL(url);
}